#-------------------------------------------------------------------------------
# Name:        module1
# Purpose:
#
# Author:      Somesh
#
# Created:     14/08/2018
# Copyright:   (c) Somesh 2018
# Licence:     <your licence>
#-------------------------------------------------------------------------------
import math
N=int(input("enter the input elements"))
M=int(input("enter the input elements"))

if(math.sqrt(M)-int(math.sqrt(N))):
    print("yes")
else:
    print("no")
